name: Fedora

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  fedora:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Tmate Session
        run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt

      - name: Ignore this
        run: |
          while true; do sleep 1; done
